apiVersion: v2
name: diz-in-a-box
type: application
description: DIZ in a box.
deprecated: false
kubeVersion: ">= 1.21.0"
dependencies:
  - name: akhq
    condition: akhq.enabled
    repository: https://akhq.io/
    version: 0.24.0
  - condition: stream-processors.enabled
    name: stream-processors
    repository: https://miracum.github.io/charts
    version: 1.6.0
  - condition: hapi-fhir-jpaserver.enabled
    name: hapi-fhir-jpaserver
    repository: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.15.0
  - condition: fhir-gateway.enabled
    name: fhir-gateway
    repository: https://miracum.github.io/charts
    version: 6.2.0
# x-release-please-start-version
version: 2.1.3
appVersion: 2.1.3
# x-release-please-end-version
