apiVersion: v2
name: prerequisites
type: application
description: Prerequisites for DIZ in a box.
deprecated: false
kubeVersion: ">= 1.21.0"
dependencies:
  - name: strimzi-kafka-operator
    repository: oci://quay.io/strimzi-helm
    version: 0.50.1
# x-release-please-start-version
version: 2.16.1
appVersion: 2.16.1
# x-release-please-end-version
