services:
  trino:
    image: docker.io/trinodb/trino:453@sha256:86f7a156aeeca1dda3a1ba1e97474913d10c75f8fb7cda0da1d29a52b5731e0c
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - $PWD/config/trino/etc:/usr/lib/trino/etc:ro
      - $PWD/config/trino/catalog:/etc/trino/catalog:ro
    depends_on:
      - hive-metastore
      - minio
